#!/bin/sh
echo "INIT SCRIPT"
mkdir /tmp
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mount -t debugfs none /sys/kernel/debug
mount -t tmpfs none /tmp
# start shelllog 
insmod /shelllog.ko
# launch shellog daemon
/shelllogd
echo -e "Boot took $(cut -d' ' -f1 /proc/uptime) seconds"
# enable root priviledge
setsid /bin/cttyhack setuidgid 0 /bin/sh
poweroff -f
